### ISSUE TITLE
OpenMP_C not found for MacOS 

### ISSUE THREAD

**Issue by romaf5** [dendibakh/perf-ninja#101]
Hi @dendibakh! Awesome labs!

CI issue with MacOS job: https://github.com/dendibakh/perf-ninja/actions/runs/11538805666/job/32117681807
`Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)`
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/39b062f6-3dc1-4209-8b5d-cae57c83b74d">

**Comment by dendibakh** [comment]
Thanks, now fixed.

**Comment by romaf5** [comment]
Thank you!
