### ISSUE TITLE
workflow CI is not running.

### ISSUE THREAD

**Issue by aschhabra** [dendibakh/perf-ninja#42]
Hello Dan,

The build is not running when pushing the code. The terminal is showing the following message

Requested labels: self-hosted, Linux
Job defined at: dendibakh/perf-ninja/.github/workflows/CI_Linux.yml@refs/heads/private/aschhabra
Waiting for a runner to pick up this job...

[![Benchmark on Linux](https://github.com/dendibakh/perf-ninja/actions/workflows/CI_Linux.yml/badge.svg?branch=private%2Faschhabra)](https://github.com/dendibakh/perf-ninja/actions/workflows/CI_Linux.yml)

**Comment by dendibakh** [comment]
Sorry, I was moving to another apartment, so my machine was down. )) Now it's back up.
