### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by goandrei** [dendibakh/perf-ninja#47]
Hi! I tried to push my private branch, but I get the following error : 

```
ERROR: Permission to dendibakh/perf-ninja.git denied to goandrei.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Is the course still free to use?

**Comment by mark2185** [comment]
Did you do [the necessary steps to allow for submissions](https://github.com/dendibakh/perf-ninja/blob/main/GetStarted.md#submission-guidelines)?

**Comment by dendibakh** [comment]
no problem
