### ISSUE TITLE
MSVC fails to build Optimize IO lab

### ISSUE THREAD

**Issue by jsjtxietian** [dendibakh/perf-ninja#70]
Hi and thank you so much for the outstanding repo !

When follow the cmake command mentioned in GetStarted.md to build the Optimize IO lab [io_opt1](https://github.com/dendibakh/perf-ninja/tree/main/labs/misc/io_opt1), msvc complains about the keyword **not** is a undeclared identifier (error C2065) , and not is used in both MappedFile.hpp and validate.hpp. For example : 
`if (not file_stream.is_open())`

It seems include the "ciso646" header will fix this issue, or one can just get rid of the three occurrences of **not** to get this code compiled with msvc. I'm willing to make a PR for this issue and hope to get your advice.

**Comment by jsjtxietian** [comment]
huge page lab suffers from this "problem" too

**Comment by dendibakh** [comment]
OK, we should get rid of using `not` keywords. Feel free to submit a PR.
