### ISSUE TITLE
Any guide on how to profiling and finding bottleneck on MacOSX?

### ISSUE THREAD

**Issue by delguoqing** [dendibakh/perf-ninja#72]
I see we have a series of videos on using perf tools and VTunes.
Neither works on MacOSX, unfortunately.

PMCs are actually available on MacOSX, but I didn't find something I can use to apply, like TMA.

**Comment by liangzhongkai** [comment]
您的来信我已收到，谢谢

**Comment by dendibakh** [comment]
Hello @delguoqing, I'm not an expert on perf engineering on Macs, but you can use Instruments that’s part of the Xcode. It gives you all the basic PMCs. Not sure about topdown as on ARMs it is slightly different than x86.

**Comment by delguoqing** [comment]
thanks. I'll close this issue

**Comment by dendibakh** [comment]
@delguoqing, if you're interested, I wrote a section about Xcode Instruments in my book:
https://github.com/dendibakh/perf-book/pull/30/commits/34d2827ee9afb3b6b0351592d439f4312b2a621c
The rendered PDF is here: https://github.com/dendibakh/perf-book/actions/runs/5953862771 (check artifacts)
Comments and reviews are welcome. :)
