### ISSUE TITLE
Debug symbols not showing up in perf

### ISSUE THREAD

**Issue by Ivan-Z** [dendibakh/perf-ninja#73]
Hello,
I've followed the quick start guide to set up the warmup lab on Linux twice on two separate machines, but I can't seem to see the source code annotations in perf. I get the same error in gdb, where it says no debug symbols found, but when I run file it says that they are there:
```
$file lab
lab: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=e2149a7abc22c14fc609c3023d2e0916752e1cec, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Any ideas?

**Comment by mark2185** [comment]
How do you compile it, could you post the entire command?

**Comment by dendibakh** [comment]
I hope this would help: https://github.com/dendibakh/perf-ninja/blob/main/GetStarted.md#profiling

**Comment by liangzhongkai** [comment]
您的来信我已收到，谢谢
