### ISSUE TITLE
Any hint about conditional_store_1 and virtual_call_mispredict?

### ISSUE THREAD

**Issue by OneMore14** [dendibakh/perf-ninja#83]
no idea how to solve them, hope to get some hints, thanks.

**Comment by liangzhongkai** [comment]
您的来信我已收到，谢谢

**Comment by dendibakh** [comment]
Spoiler:
conditional_store_1 solution: (replace branch with arithmetic instructions) https://github.com/dendibakh/perf-ninja/commit/51fd6f6860edf01e7ca1dec006d6c8c64a19ca78
virtual_call_mispredict solution: (sort the order of polymorphic objects in a container) https://github.com/dendibakh/perf-ninja/commit/ddce7b0e3f0beb2a1364de8788510d535cf5f71c

**Comment by OneMore14** [comment]
thanks, really helpful
