### ISSUE TITLE
Can't access , Permission to dendibakh/perf-ninja.git denied to 1100fe

### ISSUE THREAD

**Issue by 1100fe** [dendibakh/perf-ninja#84]
I can't push change , the steps to reproduce, 

git clone https://github.com/dendibakh/perf-ninja.git
git checkout -b private/1100fe
git push origin private/1100fe

root@leon:/data_disk/ddrFe/nijia_perf/perf-ninja# git push origin private/1100fe
remote: Permission to dendibakh/perf-ninja.git denied to 1100fe.
fatal: unable to access 'https://github.com/dendibakh/perf-ninja.git/': The requested URL returned error: 403

Would you please help me for this issue ? I have been invited to collaborate.

**Comment by dendibakh** [comment]
Try cloning with
git@github.com:dendibakh/perf-ninja.git

**Comment by 1100fe** [comment]
Thanks!
After I clone with this link, the issue is solved! O(∩_∩)O

**Comment by dendibakh** [comment]
Glad it helped

**Comment by Farravid** [comment]
Hey, I have cloned the repository using SSH too but I'm not able to submit my branch.
I haven't been invited to collaborate, not sure how to do that.

Thanks!

**Comment by dendibakh** [comment]
Please follow directions here: https://github.com/dendibakh/perf-ninja/blob/main/GetStarted.md#submission-guidelines

**Comment by Farravid** [comment]
My bad, so sorry, thanks!
