### ISSUE TITLE
Memory Order Violation lab: `An IO problem` happens when load `coins.pgm` for the first time on windows

### ISSUE THREAD

**Issue by jsjtxietian** [dendibakh/perf-ninja#88]
Hi thanks for the new lab.

When running the new lab on my windows machine, I noticed that the coin benchmark doesn't have any data due to an io problem. Looking closely, when reading `coins.pgm` for the first time, the `c` down here will be `\r` instead of `\n`, so the `GrayscaleImage::load` failed, strange enough, the second time reading `coins.pgm`, the `c` here is '\n'. 

https://github.com/dendibakh/perf-ninja/blob/64e9d4bed2fa54554174be380bcffb2ba21a92f5/labs/memory_bound/mem_order_violation_1/solution.cpp#L86-L88

I suspect it's windows being nasty again, for me I solved this issue by add these lines, consume the `\r` here:
```
if (c == '\r') {
    input >> c;
}
```

**Comment by dendibakh** [comment]
Thank you for reporting this. I didn't see it in my own testing. Even on Windows it was working fine.
Anyway, I changed coins.pgm from LF to CRLF as in other images. Commit: https://github.com/dendibakh/perf-ninja/commit/6fdd0f67bc59ec771a96f7d8fe8d7171d758e0c7

**Comment by dendibakh** [comment]
And I also included your fix (https://github.com/dendibakh/perf-ninja/commit/a9b49691f5a3b4e3bb69d5b821d69ecf73f2f0b9):
```cpp
if (c == '\r')
  input >> c;
```

**Comment by dendibakh** [comment]
@jsjtxietian, on my devices it now passes. Please check on your side.

**Comment by jsjtxietian** [comment]
The code works (I just tried another win machine it doesn't have this issue just like you)

The new coins doesn't look fine on my machine:

How it should look like:
![image](https://github.com/dendibakh/perf-ninja/assets/8315986/a04aa8d0-9dd2-4e64-9edb-371d9682cf60)

How it looks like now:
![image](https://github.com/dendibakh/perf-ninja/assets/8315986/68020e66-ed57-467a-b3bf-437f6f7d1a3f)

I suppose we should revert the image commit and just keep the code fix?

**Comment by dendibakh** [comment]
Ok, done. Thanks again @jsjtxietian
