### ISSUE TITLE
Warmup benchmark CI not running

### ISSUE THREAD

**Issue by suhasghorp** [dendibakh/perf-ninja#98]
I am following the example in the warmup video and have pushed my private branch to github. None of the workflows are triggering, even after 30 minutes. I have canceled and restarted workflows many times.

![image](https://github.com/user-attachments/assets/3c992ba8-d279-41c7-9695-b02d57631b52)

Any idea what's wrong?
Thanks

**Comment by JonathanHallstrom** [comment]
Just a guess here but maybe you're not a contributor/this is on a fork of the repo as opposed to your own branch? I would have a look at the bottom of [the setup guide](https://github.com/dendibakh/perf-ninja/blob/main/GetStarted.md).

**Comment by dendibakh** [comment]
@suhasghorp, I added you as a collaborator. Push your changes in your private branch. Don't submit pull requests.
https://github.com/dendibakh/perf-ninja/blob/main/GetStarted.md#submission-guidelines

**Comment by suhasghorp** [comment]
@dendibakh  @JonathanHallstrom  I was able to run the CI pipelines now. I had foked the original repo and was pushing my changes there, which obviously didn't work. So you need to git clone dendibakh/perf-ninja repo to your local machine, create a branch and then push it to dendibakh/perf-ninja (after you have been added a collaborator). Thank you!
